name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
      - master
      
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Read .nvmrc file
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
          
      - name: Install next
        run: npm install next
      
      - run: npm run build
       
      - run: npm install -g firebase-tools 
      
      - run: firebase deploy --non-interactive --token '${{ secrets.FIREBASE_TOKEN }}' --project dev-oasis
